{% set name = "acgc" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/acgc-{{ version }}.tar.gz
  sha256: 1e9e44e5000f366941903eb8d629184537fa528b60d65088bce9eee06171cd80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - matplotlib-inline
    - cartopy
    - numpy
    - scipy
    - pandas
    - netcdf4
    - scikit-learn
    - statsmodels
    - cmcrameri

test:
  imports:
    - acgc
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/cdholmes/acgc-python
  doc_url: https://cdholmes.github.io/acgc-python
  dev_url: https://github.com/cdholmes/acgc-python
  summary: A collection of data analysis programs used by the Atmospheric Chemistry and Global Change (ACGC) research group
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cdholmes
